config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transport_systems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transport_system.rb
class TransportSystem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transport_systems_controller.rb
class TransportSystemsController < ApplicationController
  before_action :set_transport_system, only: %i[ show edit update destroy ]

  # GET /transport_systems or /transport_systems.json
  def index
    @transport_systems = TransportSystem.all
  end

  # GET /transport_systems/1 or /transport_systems/1.json
  def show
  end

  # GET /transport_systems/new
  def new
    @transport_system = TransportSystem.new
  end

  # GET /transport_systems/1/edit
  def edit
  end

  # POST /transport_systems or /transport_systems.json
  def create
    @transport_system = TransportSystem.new(transport_system_params)

    respond_to do |format|
      if @transport_system.save
        format.html { redirect_to @transport_system, notice: "Transport system was successfully created." }
        format.json { render :show, status: :created, location: @transport_system }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transport_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transport_systems/1 or /transport_systems/1.json
  def update
    respond_to do |format|
      if @transport_system.update(transport_system_params)
        format.html { redirect_to @transport_system, notice: "Transport system was successfully updated." }
        format.json { render :show, status: :ok, location: @transport_system }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transport_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transport_systems/1 or /transport_systems/1.json
  def destroy
    @transport_system.destroy
    respond_to do |format|
      format.html { redirect_to transport_systems_url, notice: "Transport system was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport_system
      @transport_system = TransportSystem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transport_system_params
      params.require(:transport_system).permit(:name, :model)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transport_systems_helper.rb
module TransportSystemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehicle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transport_systems/_form.html.erb
<%= form_with(model: transport_system) do |form| %>
  <% if transport_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transport_system.errors.count, "error") %> prohibited this transport_system from being saved:</h2>

      <ul>
        <% transport_system.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.number_field :model %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transport_systems/edit.html.erb
<h1>Editing Transport System</h1>

<%= render 'form', transport_system: @transport_system %>

<%= link_to 'Show', @transport_system %> |
<%= link_to 'Back', transport_systems_path %>

app/views/transport_systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transport Systems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transport_systems.each do |transport_system| %>
      <tr>
        <td><%= transport_system.name %></td>
        <td><%= transport_system.model %></td>
        <td><%= link_to 'Show', transport_system %></td>
        <td><%= link_to 'Edit', edit_transport_system_path(transport_system) %></td>
        <td><%= link_to 'Destroy', transport_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport System', new_transport_system_path %>

app/views/transport_systems/new.html.erb
<h1>New Transport System</h1>

<%= render 'form', transport_system: @transport_system %>

<%= link_to 'Back', transport_systems_path %>

app/views/transport_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transport_system.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @transport_system.model %>
</p>

<%= link_to 'Edit', edit_transport_system_path(@transport_system) %> |
<%= link_to 'Back', transport_systems_path %>